import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import ReduxProvider from '../store/ReduxProvider';
import './globals.css';
import AuthWrapper from '@/components/auth/AuthWrapper';
const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${montserrat.variable}`}>
        <ReduxProvider>
          <AuthWrapper>{children}</AuthWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
